---
title: "Advent of Code Day 02"
author: "Brian A. Danielak"
date: "12/3/2020"
output: html_document
---

# Part 1

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(glue)
library(magrittr)
library(readr)
library(stringr)
```

```{r}
raw_input <-
  readr::read_table("puzzle-input.txt", col_names = "input")
```

```{r}
# example <- tibble::tibble(input = "13-16 k: kkkkkgmkbvkkrskhd")

clean_data <- function(raw_input) {
  return(
    raw_input %>%
      tidyr::separate(input, into = c("reqs", "password"), sep = ":") %>%
      tidyr::separate(
        reqs,
        into = c("limits", "req_letter"),
        sep = " "
      ) %>%
      tidyr::separate(
        limits,
        into = c("lower_lim", "upper_lim"),
        sep = "-"
      ) %>%
      dplyr::mutate(
        lower_limit = as.numeric(lower_lim),
        upper_limit = as.numeric(upper_lim)
      ) %>%
      tibble::as_tibble() %>% 
      dplyr::select(lower_limit, upper_limit, req_letter, password)
  )
}
  
passwords <- raw_input %>%
  clean_data() %>%
  dplyr::mutate(req_letter_count = stringr::str_count(password, req_letter))

  
passwords %>% 
  dplyr::mutate(meets_req = (req_letter_count >= lower_limit) & (req_letter_count <= upper_limit)) %>% 
  dplyr::count(meets_req) %>% 
  print()
```



# Part 2

```{r}
check_password <-
  function(password,
           req_letter,
           lower_lim,
           upper_lim) {
    pw <- password %>%
      stringr::str_split("") %>%
      purrr::flatten_chr()
    lower_letter <- pw[lower_lim]
    upper_letter <- pw[upper_lim]
    return(xor(lower_letter == req_letter,
               upper_letter == req_letter))
  }

check_password("bbcaa", "a", 1, 4)
check_password("kpkmkkckhkkkkvkk", "k", 9, 14)

passwords %>%
  head() %>%
  dplyr::mutate() %>% 
  dplyr::mutate(meets_req = check_password(password, req_letter, lower_limit, upper_limit)) %>% 
  # dplyr::filter(meets_req == TRUE)
  dplyr::count(meets_req)
  
```

